# Holter
holter:
    resource: "@JiabinHolterBundle/Resources/config/routing/routing.yml"
    prefix:   /

# FOS User
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"